import {
  AlignmentType,
  Document,
  Footer,
  Header,
  HeadingLevel,
  ImageRun,
  Packer,
  PageBreak,
  PageNumberElement,
  Paragraph,
  TextRun,
} from "docx";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import PptxGenJS from "pptxgenjs";

import type {
  DocumentSection,
  DocumentType,
  StyleTokens,
  ThemePreset,
} from "@/lib/contracts/document";
import { formatPageChrome } from "@/lib/pageChrome";
import { normalizeStyleTokens } from "@/lib/styleTokensNormalize";
import { resolveExportTheme } from "@/lib/generators/theme";

export type ExportPayload = {
  title: string;
  sections: DocumentSection[];
  docType?: DocumentType;
  theme?: ThemePreset;
  tone?: "professional" | "academic" | "startup";
  styleTokens?: StyleTokens;
  generatedBy?: string;
  generatedAt?: string;
};

const marginX = 50;
const marginTop = 760;

async function fetchImageAsset(url: string) {
  const response = await fetch(url);
  if (!response.ok) {
    return null;
  }
  const contentType = response.headers.get("content-type") ?? "image/jpeg";
  const bytes = Buffer.from(await response.arrayBuffer());
  return { bytes, contentType };
}

function wrapText(text: string, maxLen = 95) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word;
    if (candidate.length > maxLen) {
      lines.push(current);
      current = word;
    } else {
      current = candidate;
    }
  }

  if (current) {
    lines.push(current);
  }

  return lines;
}

function hexToRgbComponents(hex: string): { r: number; g: number; b: number } {
  const h = hex.trim().replace("#", "");
  if (h.length !== 6 || Number.isNaN(parseInt(h, 16))) {
    return { r: 0.1, g: 0.1, b: 0.1 };
  }
  return {
    r: parseInt(h.slice(0, 2), 16) / 255,
    g: parseInt(h.slice(2, 4), 16) / 255,
    b: parseInt(h.slice(4, 6), 16) / 255,
  };
}

export function asPlainText({ title, sections }: ExportPayload) {
  return [
    title,
    "",
    ...sections.flatMap((section, index) => [
      `${index + 1}. ${section.title}`,
      section.body,
      ...(section.bullets ?? []).map((bullet) => `- ${bullet}`),
      ...(section.latex ? [`LaTeX: ${section.latex}`] : []),
      ...(section.images ?? []).map((image) => `Image: ${image.url}`),
      "",
    ]),
  ].join("\n");
}

export async function exportToPdfBuffer(payload: ExportPayload) {
  const pdf = await PDFDocument.create();
  const tone = payload.tone ?? "professional";
  const st = normalizeStyleTokens(payload.styleTokens);
  const theme = resolveExportTheme(st.theme ?? payload.theme, tone);
  const headingFont = await pdf.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await pdf.embedFont(StandardFonts.Helvetica);
  const headingSize = st.headingSize;
  const bodySize = st.bodySize;
  const lineHeight = Math.round(bodySize * st.lineHeight);
  const includeCoverPage = st.includeCoverPage;
  const includeToc = st.includeToc;
  const wrapMaxLen =
    st.contentWidth === "narrow" ? 80 : st.contentWidth === "wide" ? 105 : 90;
  const accentRgb = rgb(
    parseInt(theme.accentColor.slice(1, 3), 16) / 255,
    parseInt(theme.accentColor.slice(3, 5), 16) / 255,
    parseInt(theme.accentColor.slice(5, 7), 16) / 255
  );
  const bodyRgb = rgb(...(() => {
    const c = hexToRgbComponents(st.bodyColor);
    return [c.r, c.g, c.b] as const;
  })());

  let page = pdf.addPage([595, 842]);
  let y = marginTop;

  if (includeCoverPage) {
    page.drawRectangle({
      x: 0,
      y: 742,
      width: 595,
      height: 100,
      color: accentRgb,
    });
    page.drawText(payload.title, {
      x: marginX,
      y: 700,
      size: Math.max(headingSize - 6, 22),
      font: headingFont,
      color: rgb(0.06, 0.09, 0.14),
    });
    page.drawText(`Type: ${payload.docType ?? "report"}`, {
      x: marginX,
      y: 672,
      size: bodySize,
      font: bodyFont,
      color: rgb(0.2, 0.25, 0.33),
    });
    page.drawText(
      `Generated by ${payload.generatedBy ?? "Paperly AI"} on ${
        payload.generatedAt
          ? new Date(payload.generatedAt).toLocaleDateString()
          : new Date().toLocaleDateString()
      }`,
      {
        x: marginX,
        y: 652,
        size: Math.max(bodySize - 2, 10),
        font: bodyFont,
        color: rgb(0.36, 0.42, 0.5),
      }
    );
  }

  if (includeToc) {
    page = pdf.addPage([595, 842]);
    y = marginTop;
    page.drawText("Table of Contents", {
      x: marginX,
      y,
      size: Math.max(headingSize - 10, 18),
      font: headingFont,
      color: rgb(0.06, 0.09, 0.14),
    });
    y -= 28;
    payload.sections.forEach((section, index) => {
      page.drawText(`${index + 1}. ${section.title}`, {
        x: marginX,
        y,
        size: bodySize,
        font: bodyFont,
        color: rgb(0.1, 0.1, 0.1),
      });
      y -= 18;
    });
  }

  // Main content
  page = pdf.addPage([595, 842]);
  y = marginTop;

  const drawLine = (text: string, size = 12) => {
    if (y < 78) {
      page = pdf.addPage([595, 842]);
      y = marginTop;
    }
    const isHeadingLine = size > bodySize + 1;
    page.drawText(text, {
      x: marginX,
      y,
      size,
      font: isHeadingLine ? headingFont : bodyFont,
      color: isHeadingLine ? rgb(0.06, 0.09, 0.14) : bodyRgb,
    });
    y -= lineHeight + (size > bodySize + 1 ? 4 : 0);
  };

  drawLine(payload.title, Math.max(headingSize - 8, 20));
  y -= 4;

  for (let i = 0; i < payload.sections.length; i++) {
    const section = payload.sections[i];
    drawLine(`${i + 1}. ${section.title}`, Math.max(headingSize - 14, 15));
    wrapText(section.body, wrapMaxLen).forEach((line) =>
      drawLine(line, bodySize)
    );
    if (section.bullets?.length) {
      section.bullets.forEach((bullet) =>
        drawLine(`• ${bullet.replace(/\u2022/g, "")}`, Math.max(bodySize - 1, 11))
      );
    }
    if (section.latex) {
      drawLine(`LaTeX: ${section.latex}`, Math.max(bodySize - 1, 11));
    }
    if (section.table) {
      drawLine(
        `Table: ${section.table.columns.join(" | ")}`,
        Math.max(bodySize - 1, 11)
      );
      section.table.rows
        .slice(0, 6)
        .forEach((row) => drawLine(row.join(" | "), Math.max(bodySize - 1, 11)));
    }
    if (section.chart) {
      const chart = section.chart;
      drawLine(
        `Chart (${chart.type}): ${chart.title}`,
        Math.max(bodySize - 1, 11)
      );
      const zipped = chart.labels.map((label, index) => ({
        label,
        value: chart.values[index] ?? 0,
      }));
      zipped
        .slice(0, 8)
        .forEach((entry) =>
          drawLine(`${entry.label}: ${entry.value}`, Math.max(bodySize - 1, 11))
        );
    }
    if (section.images?.length) {
      for (const image of section.images.slice(0, 3)) {
        try {
          const asset = await fetchImageAsset(image.url);
          if (!asset) {
            drawLine(
              `Image: ${image.caption ?? image.alt ?? image.url}`,
              Math.max(bodySize - 1, 11)
            );
            continue;
          }
          const embedded =
            asset.contentType.includes("png") ||
            image.url.toLowerCase().endsWith(".png")
              ? await pdf.embedPng(asset.bytes)
              : await pdf.embedJpg(asset.bytes);
          const desiredWidth = Math.max(
            120,
            Math.min(500, (500 * (image.widthPct ?? 70)) / 100)
          );
          const scale = desiredWidth / embedded.width;
          const desiredHeight = embedded.height * scale;

          if (y - desiredHeight < 82) {
            page = pdf.addPage([595, 842]);
            y = marginTop;
          }
          page.drawImage(embedded, {
            x: marginX,
            y: y - desiredHeight,
            width: desiredWidth,
            height: desiredHeight,
          });
          y -= desiredHeight + 10;

          if (image.caption || image.alt) {
            drawLine(
              `Image: ${image.caption ?? image.alt ?? ""}`,
              Math.max(bodySize - 1, 11)
            );
          }
        } catch {
          drawLine(
            `Image: ${image.caption ?? image.alt ?? image.url}`,
            Math.max(bodySize - 1, 11)
          );
        }
      }
    }
    y -= 8;
  }

  const pagesOut = pdf.getPages();
  const totalPages = pagesOut.length;
  const headerLine =
    st.showRunningHeader ? formatPageChrome(st.headerText, { title: payload.title }) : "";
  const footerChrome =
    st.showRunningFooter ? formatPageChrome(st.footerText, { title: payload.title }) : "";
  const mutedFooter = rgb(0.45, 0.45, 0.45);
  const footerSize = Math.max(8, bodySize - 3);

  pagesOut.forEach((p, index) => {
    const { height } = p.getSize();
    if (headerLine.trim()) {
      const clipped = headerLine.length > 110 ? `${headerLine.slice(0, 107)}…` : headerLine;
      p.drawText(clipped, {
        x: marginX,
        y: height - 30,
        size: footerSize,
        font: bodyFont,
        color: mutedFooter,
      });
    }
    const parts: string[] = [];
    if (footerChrome.trim()) {
      parts.push(footerChrome.length > 80 ? `${footerChrome.slice(0, 77)}…` : footerChrome);
    }
    if (st.showPageNumbers && st.pageNumberPosition === "footer") {
      parts.push(`Page ${index + 1} of ${totalPages}`);
    }
    if (parts.length === 0) {
      return;
    }
    const line = parts.join(" · ");
    const clipped = line.length > 130 ? `${line.slice(0, 127)}…` : line;
    p.drawText(clipped, {
      x: marginX,
      y: 22,
      size: footerSize,
      font: bodyFont,
      color: mutedFooter,
    });
  });

  return Buffer.from(await pdf.save());
}

export async function exportToDocxBuffer(payload: ExportPayload) {
  const tone = payload.tone ?? "professional";
  const st = normalizeStyleTokens(payload.styleTokens);
  const theme = resolveExportTheme(st.theme ?? payload.theme, tone);
  const includeCoverPage = st.includeCoverPage;
  const includeToc = st.includeToc;
  const headingSize = st.headingSize;
  const bodySize = st.bodySize;

  const footerRuns: (TextRun | PageNumberElement)[] = [];
  const footerChromeFormatted = st.showRunningFooter ?
    formatPageChrome(st.footerText, { title: payload.title })
  : "";
  if (footerChromeFormatted.trim()) {
    footerRuns.push(
      new TextRun({
        text: `${footerChromeFormatted} · `,
        size: 18,
        color: "64748B",
      })
    );
  }
  if (st.showPageNumbers && st.pageNumberPosition === "footer") {
    footerRuns.push(
      new TextRun({ text: "Page ", size: 18, color: "64748B" }),
      new PageNumberElement()
    );
  }
  if (footerRuns.length === 0) {
    footerRuns.push(
      new TextRun({
        text: "Paperly AI",
        size: 18,
        color: "64748B",
      })
    );
  }

  const footer = new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.RIGHT,
        children: footerRuns,
      }),
    ],
  });

  const headerTextFormatted =
    st.showRunningHeader ? formatPageChrome(st.headerText, { title: payload.title }) : "";
  const header =
    headerTextFormatted.trim() ?
      new Header({
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: headerTextFormatted.slice(0, 200),
                size: 18,
                color: "475569",
              }),
            ],
          }),
        ],
      })
    : null;

  const paragraphs: Paragraph[] = [];

  if (includeCoverPage) {
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: payload.title,
            bold: true,
            size: headingSize * 2,
            color: theme.headingColor.replace("#", ""),
          }),
        ],
        heading: HeadingLevel.HEADING_1,
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Type: ${payload.docType ?? "report"} | Theme: ${theme.theme}`,
            size: bodySize * 2,
            color: "475569",
          }),
        ],
        spacing: { after: 320 },
      }),
      new Paragraph({
        children: [new PageBreak()],
      })
    );
  }

  if (includeToc) {
    paragraphs.push(
      new Paragraph({
        text: "Table of Contents",
        heading: HeadingLevel.HEADING_1,
      })
    );
  }

  if (includeToc) {
    payload.sections.forEach((section, index) => {
      paragraphs.push(
        new Paragraph({
          text: `${index + 1}. ${section.title}`,
        })
      );
    });
    paragraphs.push(
      new Paragraph({
        children: [new PageBreak()],
      })
    );
  }

  for (const [index, section] of payload.sections.entries()) {
    paragraphs.push(
      new Paragraph({
        text: `${index + 1}. ${section.title}`,
        heading: HeadingLevel.HEADING_2,
      })
    );
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: section.body,
            color: theme.bodyColor.replace("#", ""),
            size: bodySize * 2,
          }),
        ],
      })
    );
    section.bullets?.forEach((bullet) => {
      paragraphs.push(
        new Paragraph({
          bullet: { level: 0 },
          children: [new TextRun(bullet)],
        })
      );
    });
    if (section.table) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `Table: ${section.table.columns.join(" | ")}`,
              italics: true,
            }),
          ],
        })
      );
      section.table.rows.forEach((row) => {
        paragraphs.push(new Paragraph({ text: row.join(" | ") }));
      });
    }
    if (section.latex) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `LaTeX: ${section.latex}`,
              italics: true,
            }),
          ],
        })
      );
    }
    if (section.images?.length) {
      for (const image of section.images.slice(0, 3)) {
        try {
          const asset = await fetchImageAsset(image.url);
          if (!asset) {
            paragraphs.push(
              new Paragraph({
                text: `Image: ${image.caption ?? image.alt ?? image.url}`,
              })
            );
            continue;
          }
          paragraphs.push(
            new Paragraph({
              children: [
                new ImageRun({
                  data: asset.bytes,
                  type: asset.contentType.includes("png") ? "png" : "jpg",
                  transformation: {
                    width: 520,
                    height: 290,
                  },
                }),
              ],
            })
          );
          if (image.caption || image.alt) {
            paragraphs.push(
              new Paragraph({
                children: [
                  new TextRun({
                    text: image.caption ?? image.alt ?? "",
                    italics: true,
                  }),
                ],
              })
            );
          }
        } catch {
          paragraphs.push(
            new Paragraph({
              text: `Image: ${image.caption ?? image.alt ?? image.url}`,
            })
          );
        }
      }
    }
  }

  const doc = new Document({
    sections: [
      {
        properties: {},
        ...(header ? { headers: { default: header } } : {}),
        footers: { default: footer },
        children: paragraphs,
      },
    ],
  });

  return Packer.toBuffer(doc);
}

export async function exportToPptxBuffer(payload: ExportPayload) {
  const tone = payload.tone ?? "professional";
  const theme = resolveExportTheme(
    payload.styleTokens?.theme ?? payload.theme,
    tone
  );
  const headingSize = payload.styleTokens?.headingSize ?? 30;
  const bodySize = payload.styleTokens?.bodySize ?? 13;
  const includeCoverPage = payload.styleTokens?.includeCoverPage ?? true;

  const pptx = new PptxGenJS();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Paperly AI";
  pptx.subject = "AI-generated professional document";
  pptx.title = payload.title;

  if (includeCoverPage) {
    const cover = pptx.addSlide();
    cover.background = { color: "F8FAFC" };
    cover.addShape(pptx.ShapeType.roundRect, {
      x: 0.4,
      y: 0.5,
      w: 12.4,
      h: 0.25,
      fill: { color: theme.accentColor.replace("#", "") },
      line: { color: theme.accentColor.replace("#", "") },
    });
    cover.addText(payload.title, {
      x: 0.7,
      y: 1.1,
      w: 12,
      h: 1.2,
      bold: true,
      fontSize: Math.max(headingSize + 4, 30),
      color: theme.titleColor.replace("#", ""),
    });
    cover.addText("Generated by Paperly AI", {
      x: 0.7,
      y: 2.5,
      w: 8,
      h: 0.5,
      fontSize: bodySize + 2,
      color: "475569",
    });
    cover.addText(`Type: ${payload.docType ?? "report"}`, {
      x: 0.7,
      y: 3,
      w: 10,
      h: 0.4,
      fontSize: bodySize,
      color: "334155",
    });
  }

  for (const [slideIndex, section] of payload.sections.slice(0, 6).entries()) {
    const slide = pptx.addSlide();
    slide.background = { color: "FFFFFF" };
    slide.addText(`${slideIndex + 1}. ${section.title}`, {
      x: 0.6,
      y: 0.5,
      w: 12,
      h: 0.7,
      bold: true,
      fontSize: Math.max(headingSize - 6, 22),
      color: theme.headingColor.replace("#", ""),
    });
    slide.addText(section.body, {
      x: 0.8,
      y: 1.4,
      w: 11.5,
      h: 4.5,
      fontSize: bodySize + 2,
      color: theme.bodyColor.replace("#", ""),
      valign: "top",
    });
    if (section.bullets?.length) {
      slide.addText(
        section.bullets.slice(0, 5).map((item) => ({
          text: item,
          options: { bullet: { indent: 20 } },
        })),
        {
          x: 0.9,
          y: 3.8,
          w: 11,
          h: 2.4,
          fontSize: bodySize,
          color: "334155",
        }
      );
    }
    if (section.latex) {
      slide.addText(`LaTeX: ${section.latex}`, {
        x: 0.8,
        y: 6,
        w: 11.2,
        h: 0.4,
        fontSize: Math.max(bodySize - 1, 11),
        color: "334155",
      });
    }
    if (section.images?.length) {
      const image = section.images[0];
      try {
        const asset = await fetchImageAsset(image.url);
        if (asset) {
          const dataUri = `data:${asset.contentType};base64,${asset.bytes.toString("base64")}`;
          slide.addImage({
            data: dataUri,
            x: 8.2,
            y: 4.2,
            w: 4,
            h: 2.1,
          });
        } else {
          slide.addText(`Image: ${image.caption ?? image.alt ?? image.url}`, {
            x: 0.8,
            y: 6.3,
            w: 11.2,
            h: 0.4,
            fontSize: Math.max(bodySize - 1, 11),
            color: "64748B",
          });
        }
      } catch {
        slide.addText(`Image: ${image.caption ?? image.alt ?? image.url}`, {
          x: 0.8,
          y: 6.3,
          w: 11.2,
          h: 0.4,
          fontSize: Math.max(bodySize - 1, 11),
          color: "64748B",
        });
      }
    }
  }

  return (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
}
